### ISSUE TITLE
Blackfathom Deeps: Fathom Stone GO

### ISSUE THREAD

**Issue by Undergarun** [scriptdev2/scriptdev2-tbc#14]
http://www.wowhead.com/object=177964/fathom-stone should be spawned when Baron Aquanis is killed in order to complete http://www.wowhead.com/quest=6921/amongst-the-ruins and start next quest in line.

**Comment by xfurry** [comment]
https://github.com/scriptdev2/scriptdev2/commit/0f76bcd9c163399a5cd73cc27c16c26451b31099

Will be backported soonish.
